// <auto-generated />
namespace taxinoibai.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class addnull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addnull));
        
        string IMigrationMetadata.Id
        {
            get { return "202509290623203_add-null"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
